
export const taoQuotes = [
"Heaven and Earth are not kind. They regard all things as offerings.",
"Is not the space between Heaven and Earth like a bellows? It is empty, but lacks nothing. The more it moves, the more comes out of it.",
"All things arise in unison. Thereby we see their return.",
"All things flourish, and each returns to its source.",
"Strong winds do not last all morning, hard rains do not last all day.",
"If Heaven and Earth are unable to persist, how could man?",
"Man is ruled by Earth. Earth is ruled by Heaven. Heaven is ruled by the Way. The Way is ruled by itself.",
"What the Way is to the world, the stream is to the river and the sea.",
"If Heaven were not clear it might rend. If Earth were not firm it might crumble.",
"All things carry yin and embrace yang. They reach harmony by blending with the vital breath.",
"Of all things, none does not revere the Way and honor virtue. Reverence of the Way and honoring virtue were not demanded of them, but it is in their nature.",
"The river and the sea can be kings of a hundred valleys, because they lie below them.",
"Conquering the world and changing it, I do not think it can succeed.",
"The world is a sacred vessel that cannot be changed. He who changes it will destroy it. He who seizes it will lose it.",
"Never take over the world to tamper with it. Those who want to tamper with it are not fit to take over the world.",
"The Way that can be walked is not the eternal Way.",
"The Way is empty, yet inexhaustible, like an abyss!",
"Obscure, like muddy waters.",
"The Way is eternal. Until your last day, you are free from peril.",
"I do not know its name. I call it the Way. For the lack of better words I call it great.",
"The Way is ever nameless.",
"The great Way is all-pervading. It reaches to the left and to the right. All things depend on it with their existence. Still it demands no obedience.",
"It (Tao) is eternally without desire. So, it can be called small. All things return to it, although it does not make itself their ruler. So, it can be called great.",
"Words spoken about the Way have no taste. When looked at, there’s not enough to see. When listened to, there’s not enough to hear. When used, it is never exhausted.",
"Returning is the movement of the Way.",
"The light of the Way seems dim.",
"The progress of the Way seems retreating.",
"The straightness of the Way seems curved.",
"The Way is hidden and nameless. Still only the Way nourishes and completes.",
"The whole world says that my Way is great like nothing else. It is great because it is like nothing else. If it were like everything else, it would long ago have become insignificant.",
"Heaven’s Way does not contend, yet it certainly triumphs. It does not speak, yet it certainly answers. It does not summon, yet things come by themselves. It seems to be at rest, yet it certainly has a plan.",
"Heaven’s net is very vast. It is sparsely meshed, yet nothing slips through.", 
"The nameless is the beginning of Heaven and Earth. The named is the mother of all things.",
"From now back to antiquity, its (Tao's) name has not been lost. Thereby, see the origin of all.",
"There was something that finished chaos, born before Heaven and Earth.",
"All things in the world are born out of being. Being is born out of non-being.",
"The world’s beginning is its mother. To have found the mother is also to know the children. Although you know the children, cling to the mother. Until your last day you will not be harmed.",
"Can you make your soul embrace the One and not lose it?",
"Hold on to the ancient Way to master the present, and to learn the distant beginning.",
"Knowledge of the eternal is all-embracing. To be all-embracing leads to righteousness, which is majestic.",
"I alone am different from the others, because I am nourished by the great mother.",
"The greatest virtue is to follow the Way utterly.",
"The sage embraces the one, and is an example to the world.",
"Hold on to the great image, and the whole world follows, follows unharmed, content and completely at peace.",
"If I have just an ounce of sense, I follow the great Way, and fear only to stray from it.",
"Profound virtue is indeed deep and wide. It leads all things back to the great order.",
"When the great Way is abandoned, benevolence and righteousness arise.",
"Things exalted then decay. This is going against the Way. What goes against the Way meets an early end.",
"The great Way is very straight, but people prefer to deviate.",
"When wisdom and knowledge appear, great pretense arises.",
"Those who understand others are clever, those who understand themselves are wise.",
"The more clever and cunning people are, the stranger the events will be.",
"People are difficult to rule, because of their knowledge.",
"Not knowing of the eternal leads to unfortunate errors.",
"Those who know it do not speak about it. Those who speak about it do not know it.",
"Correct becomes defect. Good becomes ominous. People’s delusions have certainly lasted long.",
"Knowing that you do not know is the best. Not knowing that you do not know is an illness.",
"Truly, only those who see illness as illness can avoid illness.",
"The sage is not ill, because he sees illness as illness.",
"True words seem false.",
"True words are not pleasing. Pleasing words are not true.",
"Those who are right do not argue. Those who argue are not right.",
"Those who know are not learned. Those who are learned do not know.",
"Abandon wisdom, discard knowledge, and people will benefit a hundredfold.",
"Abandon knowledge and your worries are over.",
"I have the mind of a fool, understanding nothing.",
"Those who seek knowledge, collect something every day. Those who seek the Way, let go of something every day.",
"My words are very easy to understand and very easy to practice. Still, no one in the world can understand or practice them.",
"My words have an origin. My deeds have a sovereign. Truly, because people do not understand this, they do not understand me.",
"That so few understand me is why I am treasured.",
"A good person is the bad person’s teacher. A bad person is the good person’s task.",
"The one who does not honor the teacher and the one who does not honor the task, although ever so knowledgeable, they are confused.",
"The superior student listens to the Way and follows it closely. The average student listens to the Way and follows some and some not. The lesser student listens to the Way and laughs out loud. If there were no laughter it would not be the Way.",
"Sometimes gain comes from losing, and sometimes loss comes from gaining.",
"What has no substance can penetrate what has no opening.",
"The most complete seems lacking. Yet in use it is not exhausted.",
"The most abundant seems empty. Yet in use it is not drained.",
"The most straight seems curved.",
"The most able seems clumsy.",
"The most eloquent seems to stutter.",
"Taste the tasteless.",
"Make the small big and the few many.",
"Thirty spokes are joined in the wheel’s hub. The hole in the middle makes it useful.",
"Mold clay into a bowl. The empty space makes it useful.",
"Cut out doors and windows for the house. The holes make it useful.",
"The value comes from what is there, but the use comes from what is not there.",
"The sage acts by doing nothing.",
"Can you comprehend everything in the four directions and still do nothing?",
"Because he (the Sage) opposes no one, no one in the world can oppose him.",
"The Way is ever without action, yet nothing is left undone.",
"The highest virtue does nothing. Yet, nothing needs to be done. The lowest virtue does everything. Yet, much remains to be done.",
"The value of teaching without words and accomplishing without action is understood by few in the world.",
"The sage knows without traveling, perceives without looking, completes without acting.",
"When nothing is done, nothing is left undone.",
"Use justice to rule a country. Use surprise to wage war. Use non-action to govern the world.",
"I do not act, and people become reformed by themselves.",
"I am at peace, and people become fair by themselves.",
"I do not interfere, and people become rich by themselves.",
"Act without action.",
"Those who act will fail. Those who seize will lose.",
"He (the sage) wants all things to follow their own nature, but dares not act.",
"The sage does not act and therefore does not fail, does not seize and therefore does not lose.",
"Cautious, like crossing a river in the winter.",
"Wary, as if surrounded by strangers.",
"Although he travels all day, the sage never loses sight of his luggage carts.",
"The best way to carve is not to split.",
"Those who know when to halt are unharmed.",
"Seal the openings, shut the doors, and until your last day you will not be exhausted. Widen the openings, interfere, and until your last day you will not be safe.",
"The sage is sharp but does not cut, pointed but does not pierce, forthright but does not offend, bright but does not dazzle.",
"Pursue without interfering.",
"Lightly given promises must meet with little trust.",
"Taking things lightly must lead to big difficulties.",
"The sage regards things as difficult, and thereby avoids difficulty.",
"People fail at the threshold of success. Be as cautious at the end as at the beginning. Then there will be no failure.",
"Those who have the courage to dare will perish. Those who have the courage not to dare will live.",
"The sage’s Way is to act and not to contend.",
"Seeing the small is called clarity.",
"Use the light to return to clarity.",
"Knowing the future is the flower of the Way, and the beginning of folly.",
"The truly great ones rely on substance, and not on surface, hold on to the fruit, and not to the flower.",
"Your name or your body, what is dearer? Your body or your wealth, what is worthier?",
"The separate parts make no carriage.",
"The greatest vessel takes long to complete.",
"Movement overcomes cold.",
"What is well planted will not be uprooted.",
"What is well held will not escape."
]
